import HashMap from "./hashMap.mjs";

const test = new HashMap();

// console.log(test.hash("apple"));
// console.log(test.hash("banana"));
test.set("apple", "red");
test.set("banana", "yellow");
test.set("carrot", "orange");
test.set("dog", "brown");
test.set("elephant", "gray");
test.set("frog", "green");
test.set("grape", "purple");
test.set("hat", "black");
test.set("ice cream", "white");
test.set("jacket", "blue");
test.set("kite", "pink");
test.set("lion", "golden");
// console.log(test.has("lion"));
// console.log(test.has("dog"));
// console.log(test.has("grape"));
// console.log(test.has("hat"));
// console.log(test.get("lion"));
// console.log(test.get("dog"));
// console.log(test.get("grape"));
// console.log(test.get("hat"));
// console.log(test.buckets);
// console.log(test.length());
// console.log(test.remove("kite"));
// console.log(test.remove("kite"));
// console.log(test.remove("dog"));
// console.log(test.length());
// console.log(test.remove("lion"));
// console.log(test.length());
// console.log(test.buckets);
// console.log(test.length());
// test.remove("jacket");
// console.log(test.buckets);
// console.log(test.length());
// test.clear();
// console.log(test.buckets);
// console.log(test.keys());
// console.log(test.values());
// console.log(test.entries());
// // console.log(test.entries());
// console.log(test.checkFull());
// console.log(test.length());
// console.log(test.length());
// // console.log(test.entries());
// console.log(test.checkFull());
test.set("apples", "poker");
test.set("moons", "silver");
test.set("moon", "silver");
test.set("berry", "silver");
test.set("melon", "silver");
// console.log(test.buckets);
// console.log(test.length());
console.log(test.entries().length);
console.log(test.checkFull());
console.log(test.length());
console.log(test.buckets);
